import { randomBytes } from 'node:crypto'
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, renameSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { privateKeyToAccount, generatePrivateKey } from 'viem/accounts'
import { isAddress, getAddress, type Address } from 'viem'
import { z } from 'zod'
import { createKeystore, decryptKeystore, decryptKeystoreToHex, type KeystoreFile } from '../keystore.js'
import { log } from '../log.js'

/**
 * Multi-user wallet registry for the Telegram bot.
 *
 * THIS IS A CUSTODIAL SYSTEM. The operator's machine holds private keys for
 * every user. That is a serious responsibility and the design reflects it:
 *
 *  - Keys are GENERATED here and never leave. There is no import command and
 *    no export command. A private key must never travel through Telegram,
 *    because every bot message is stored in plaintext on Telegram's servers.
 *
 *  - The only way funds leave is a withdrawal to a PRE-REGISTERED address.
 *    Changing that address is time-locked, so a hijacked Telegram account
 *    cannot redirect funds before the real owner notices.
 *
 *  - Every keystore is encrypted with a master passphrase the operator types
 *    at startup. It is never written to disk.
 *
 * The threat this defends against is the realistic one: someone takes over a
 * user's Telegram (SIM swap, session theft) and tries to drain the wallet.
 * It does NOT defend against the operator's machine being compromised. Nothing
 * here can. That risk is inherent to custody and the operator carries it.
 */

/** How long a withdrawal-address change must wait before taking effect. */
export const WITHDRAWAL_ADDRESS_LOCK_MS = 24 * 60 * 60 * 1000

const addressSchema = z
  .string()
  .refine((v) => isAddress(v), 'not a valid EVM address')
  .transform((v) => getAddress(v))

/**
 * One wallet. A user may hold several: generated by the bot, or imported from a
 * pre-funded external wallet by the operator. Exactly one is `active` and is the
 * wallet used for bridging and trading.
 */
const walletSchema = z.object({
  id: z.string().min(1),
  label: z.string().default('Wallet'),
  address: addressSchema,
  keystore: z.custom<KeystoreFile>(),
  origin: z.enum(['generated', 'imported']).default('generated'),
  createdAt: z.string(),
})

export type StoredWallet = z.infer<typeof walletSchema>

const userSchema = z.object({
  telegramId: z.number().int(),
  username: z.string().nullable().default(null),

  wallets: z.array(walletSchema).min(1),
  activeWalletId: z.string().min(1),

  /**
   * Funds can only ever be sent here. Deliberately PER-USER, not per-wallet:
   * one time-locked destination protects every wallet at once, so an attacker
   * who takes over the account cannot sidestep the 24h lock by adding a fresh
   * wallet with an unset (and therefore instantly-settable) address.
   */
  withdrawalAddress: addressSchema.nullable().default(null),
  /** A requested change, pending until the lock expires. */
  pendingWithdrawalAddress: addressSchema.nullable().default(null),
  pendingWithdrawalEffectiveAt: z.number().nullable().default(null),

  /** Per-user trade settings. Bounded by caps below. */
  spendUsdc: z.string().default('20.00'),
  bridgeUsdc: z.string().default('25.00'),
  maxSlippageBps: z.number().int().min(1).max(10_000).default(300),
  tokenAddress: addressSchema.nullable().default(null),
  armed: z.boolean().default(false),

  /** Operator-set ceilings. Users cannot raise these from Telegram. */
  caps: z
    .object({
      maxSpendUsdc: z.string().default('250.00'),
      maxBridgeUsdc: z.string().default('250.00'),
    })
    .default({ maxSpendUsdc: '250.00', maxBridgeUsdc: '250.00' }),

  /** Set by /panic. Blocks all spending until explicitly cleared. */
  frozen: z.boolean().default(false),
  createdAt: z.string(),
})

export type StoredUser = z.infer<typeof userSchema>

/** Short, collision-resistant wallet id. */
export function newWalletId(): string {
  return randomBytes(6).toString('hex')
}

/**
 * Migrate a legacy single-wallet record ({ address, keystore }) to the
 * multi-wallet shape, in memory, before validation.
 *
 * Lossless by construction: the existing keystore becomes wallet #1 and is
 * marked active, so no user can lose access to funds across the upgrade. Runs
 * on read; the migrated record is persisted on the next write (and persist() is
 * atomic, so an interrupted migration leaves the old file intact and simply
 * migrates again next start).
 */
function migrateLegacyRecord(json: unknown): unknown {
  if (!json || typeof json !== 'object') return json
  const rec = json as Record<string, unknown>
  if (Array.isArray(rec.wallets)) return json // already migrated
  if (!rec.address || !rec.keystore) return json // let validation reject it

  const id = newWalletId()
  const { address, keystore, ...rest } = rec
  return {
    ...rest,
    wallets: [
      {
        id,
        label: 'Main',
        address,
        keystore,
        origin: 'generated',
        createdAt: (rec.createdAt as string) ?? new Date().toISOString(),
      },
    ],
    activeWalletId: id,
  }
}

/** The wallet a user is currently trading with. */
export function activeWallet(user: StoredUser): StoredWallet {
  const w = user.wallets.find((x) => x.id === user.activeWalletId)
  if (!w) {
    // Should be impossible (setActiveWallet validates), but never silently sign
    // with an arbitrary wallet if it happens.
    throw new Error(`user ${user.telegramId} has no wallet matching activeWalletId ${user.activeWalletId}`)
  }
  return w
}

export const DATA_DIR = resolve(process.cwd(), 'data')
export const USERS_DIR = join(DATA_DIR, 'users')

function userPath(telegramId: number): string {
  return join(USERS_DIR, `${telegramId}.json`)
}

export class UserRegistry {
  private cache = new Map<number, StoredUser>()
  /** In-flight wallet creations, to make concurrent /start idempotent. */
  private creating = new Map<number, Promise<StoredUser>>()

  /**
   * @param masterPassphrase Unlocks every user keystore. Typed by the operator
   *   at startup and held only in memory.
   */
  /**
   * Ceilings applied to newly created/imported wallets. Comes from
   * config/telegram.json `defaultCaps`. Existing users keep the caps stored on
   * their record, so raising the default does not retroactively raise theirs.
   */
  private readonly defaultCaps: { maxSpendUsdc: string; maxBridgeUsdc: string }

  constructor(
    private readonly masterPassphrase: string,
    defaultCaps: { maxSpendUsdc: string; maxBridgeUsdc: string } = {
      maxSpendUsdc: '250.00',
      maxBridgeUsdc: '250.00',
    },
  ) {
    this.defaultCaps = defaultCaps
    mkdirSync(USERS_DIR, { recursive: true })
    this.loadAll()
  }

  private loadAll(): void {
    if (!existsSync(USERS_DIR)) return
    for (const file of readdirSync(USERS_DIR)) {
      if (file.endsWith('.tmp')) continue // leftover from an interrupted write
      if (!file.endsWith('.json')) continue
      // A malformed user record is NOT something to skip past quietly - it means
      // a keystore we hold is unreadable, i.e. someone's funds may be
      // inaccessible. Refuse to start so the operator investigates rather than
      // unknowingly running with a user silently missing.
      let raw: string
      try {
        raw = readFileSync(join(USERS_DIR, file), 'utf8')
      } catch (err) {
        throw new Error(`cannot read user record ${file}: ${(err as Error).message}`)
      }
      let json: unknown
      try {
        json = JSON.parse(raw)
      } catch {
        throw new Error(
          `user record ${file} is corrupt (invalid JSON). Refusing to start. ` +
            `Restore it from backup, or move it aside if you accept losing that wallet.`,
        )
      }
      const migrated = migrateLegacyRecord(json)
      const parsed = userSchema.safeParse(migrated)
      if (!parsed.success) {
        throw new Error(
          `user record ${file} failed validation (${parsed.error.issues.length} issues). Refusing to start.`,
        )
      }
      // A migrated record must still point at a real wallet before we accept it.
      activeWallet(parsed.data)
      this.cache.set(parsed.data.telegramId, parsed.data)
      if (migrated !== json) {
        log.info({ telegramId: parsed.data.telegramId }, 'migrated legacy single-wallet record')
        this.persist(parsed.data)
      }
    }
    log.info({ users: this.cache.size }, 'user registry loaded')
  }

  /**
   * Persist atomically: write to a temp file, then rename over the target.
   * rename() is atomic on a single filesystem, so a crash can never leave a
   * half-written keystore - the file is either the old version or the new one,
   * never a truncated middle. For a file that is the ONLY copy of a user's key,
   * this is the difference between a recoverable restart and lost funds.
   */
  private persist(user: StoredUser): void {
    mkdirSync(USERS_DIR, { recursive: true })
    const finalPath = userPath(user.telegramId)
    const tmpPath = `${finalPath}.${process.pid}.tmp`
    writeFileSync(tmpPath, JSON.stringify(user, null, 2), { mode: 0o600 })
    renameSync(tmpPath, finalPath)
    this.cache.set(user.telegramId, user)
  }

  get(telegramId: number): StoredUser | undefined {
    return this.cache.get(telegramId)
  }

  all(): StoredUser[] {
    return [...this.cache.values()]
  }

  /**
   * Create a wallet for a new user.
   *
   * The key is generated here with CSPRNG randomness and immediately encrypted.
   * It is never returned, logged, or displayed. The user receives only an
   * address to deposit to.
   */
  async create(telegramId: number, username: string | null): Promise<StoredUser> {
    const existing = this.cache.get(telegramId)
    if (existing) return existing

    // Reserve the slot synchronously before the await below. Two near-
    // simultaneous /start messages from the same user could otherwise both pass
    // the existence check, generate two keypairs, and have the second persist()
    // clobber the first - orphaning any funds sent to the first address.
    if (this.creating.has(telegramId)) return this.creating.get(telegramId)!
    const promise = this.doCreate(telegramId, username)
    this.creating.set(telegramId, promise)
    try {
      return await promise
    } finally {
      this.creating.delete(telegramId)
    }
  }

  private async doCreate(telegramId: number, username: string | null): Promise<StoredUser> {
    // viem's generatePrivateKey uses a CSPRNG. Touch randomBytes too so the
    // dependency on a secure source is explicit and auditable.
    randomBytes(32)
    const pk = generatePrivateKey()
    const account = privateKeyToAccount(pk)
    const keystore = await createKeystore(pk, this.masterPassphrase)

    const id = newWalletId()
    const now = new Date().toISOString()
    const user: StoredUser = {
      telegramId,
      username,
      wallets: [{ id, label: 'Main', address: account.address, keystore, origin: 'generated', createdAt: now }],
      activeWalletId: id,
      withdrawalAddress: null,
      pendingWithdrawalAddress: null,
      pendingWithdrawalEffectiveAt: null,
      spendUsdc: '20.00',
      bridgeUsdc: '25.00',
      maxSlippageBps: 300,
      tokenAddress: null,
      armed: false,
      caps: { ...this.defaultCaps },
      frozen: false,
      createdAt: now,
    }

    this.persist(user)
    log.info({ telegramId, address: account.address }, 'created wallet for user')
    return user
  }

  /**
   * Decrypt a signing account. Defaults to the user's ACTIVE wallet; pass a
   * walletId to unlock a specific one (e.g. withdrawing from a non-active
   * wallet). Held only for the duration of the caller's operation.
   */
  async unlock(telegramId: number, walletId?: string) {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    const wallet = walletId ? user.wallets.find((w) => w.id === walletId) : activeWallet(user)
    if (!wallet) throw new Error(`no wallet ${walletId} for user ${telegramId}`)
    return decryptKeystore(wallet.keystore, this.masterPassphrase)
  }

  /** Add a freshly generated wallet alongside the user's existing ones. */
  async addGeneratedWallet(telegramId: number, label: string): Promise<StoredWallet> {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')

    randomBytes(32)
    const pk = generatePrivateKey()
    const account = privateKeyToAccount(pk)
    const keystore = await createKeystore(pk, this.masterPassphrase)

    const wallet: StoredWallet = {
      id: newWalletId(),
      label: label.slice(0, 40) || 'Wallet',
      address: account.address,
      keystore,
      origin: 'generated',
      createdAt: new Date().toISOString(),
    }
    // Re-read AFTER the ~1s scrypt above. Persisting the stale snapshot would
    // clobber anything written during that window - including another wallet
    // whose deposit address was already shown to the user, or a /panic freeze.
    const fresh = this.cache.get(telegramId)
    if (!fresh) throw new Error('no such user')
    this.persist({ ...fresh, wallets: [...fresh.wallets, wallet] })
    log.info({ telegramId, address: wallet.address }, 'added generated wallet')
    return wallet
  }

  /** Switch which wallet trades. Validated so activeWalletId always resolves. */
  setActiveWallet(telegramId: number, walletId: string): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    if (!user.wallets.some((w) => w.id === walletId)) throw new Error('no such wallet')
    const next = { ...user, activeWalletId: walletId }
    this.persist(next)
    return next
  }

  /**
   * Remove a wallet. Refuses to remove the last one or the active one, and the
   * CALLER must have verified it is empty - dropping a keystore is irreversible.
   */
  removeWallet(telegramId: number, walletId: string): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    if (user.wallets.length <= 1) throw new Error('cannot remove your only wallet')
    if (user.activeWalletId === walletId) throw new Error('switch to another wallet before removing this one')
    const next = { ...user, wallets: user.wallets.filter((w) => w.id !== walletId) }
    this.persist(next)
    log.warn({ telegramId, walletId }, 'wallet removed - its key is gone')
    return next
  }

  /**
   * Import an externally-supplied private key. OPERATOR-ONLY, never via Telegram.
   *
   * ADDS a wallet rather than replacing the record. That is the important
   * property: importing can no longer discard an existing keystore, so it cannot
   * orphan funds. It also leaves the user-level withdrawal address (and its 24h
   * lock) intact, so importing is not a way to reset that protection.
   *
   * Creates the user if they do not exist yet.
   */
  async importExternalKey(
    telegramId: number,
    privateKey: string,
    username: string | null,
    label = 'Imported',
    makeActive = true,
  ): Promise<{ user: StoredUser; wallet: StoredWallet }> {
    const hex = privateKey.trim().startsWith('0x') ? privateKey.trim() : `0x${privateKey.trim()}`
    const account = privateKeyToAccount(hex as `0x${string}`)
    const keystore = await createKeystore(hex, this.masterPassphrase)
    const now = new Date().toISOString()

    const wallet: StoredWallet = {
      id: newWalletId(),
      label: label.slice(0, 40) || 'Imported',
      address: account.address,
      keystore,
      origin: 'imported',
      createdAt: now,
    }

    const existing = this.cache.get(telegramId)
    const user: StoredUser = existing
      ? {
          ...existing,
          username: username ?? existing.username,
          wallets: [...existing.wallets, wallet],
          activeWalletId: makeActive ? wallet.id : existing.activeWalletId,
        }
      : {
          telegramId,
          username,
          wallets: [wallet],
          activeWalletId: wallet.id,
          withdrawalAddress: null,
          pendingWithdrawalAddress: null,
          pendingWithdrawalEffectiveAt: null,
          spendUsdc: '20.00',
          bridgeUsdc: '25.00',
          maxSlippageBps: 300,
          tokenAddress: null,
          armed: false,
          caps: { ...this.defaultCaps },
          frozen: false,
          createdAt: now,
        }

    this.persist(user)
    return { user, wallet }
  }

  /**
   * Decrypt and return a raw private key hex. OPERATOR-ONLY, never over Telegram.
   * Defaults to the active wallet.
   */
  async exportPrivateKey(telegramId: number, walletId?: string): Promise<{ address: string; privateKey: string }> {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    const wallet = walletId ? user.wallets.find((w) => w.id === walletId) : activeWallet(user)
    if (!wallet) throw new Error(`no wallet ${walletId} for user ${telegramId}`)
    // decryptKeystore verifies the derived address matches the stored one, so
    // this also proves the keystore is intact.
    const account = await decryptKeystore(wallet.keystore, this.masterPassphrase)
    if (account.address !== wallet.address) throw new Error('keystore address mismatch on export')
    return { address: wallet.address, privateKey: await decryptKeystoreToHex(wallet.keystore, this.masterPassphrase) }
  }

  /**
   * Allowlist of fields the generic update path may write. Anything not named
   * here - identity, keystore, caps, and every withdrawal-address field - is
   * unreachable through update() and must go through its own guarded method.
   * An allowlist (not a denylist) means a field added later is locked down by
   * default rather than silently writable.
   */
  private static readonly UPDATABLE: ReadonlyArray<keyof StoredUser> = [
    'username',
    'spendUsdc',
    'bridgeUsdc',
    'maxSlippageBps',
    'tokenAddress',
    'armed',
    // 'frozen' is deliberately NOT here. If it were, any handler routed through
    // update() could clear it - i.e. a button could self-unfreeze an account
    // that /panic locked. Freezing goes through setFrozen(), and only an admin
    // path may unfreeze.
  ]

  update(telegramId: number, patch: Partial<StoredUser>): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    const safe: Partial<StoredUser> = {}
    for (const key of UserRegistry.UPDATABLE) {
      if (key in patch) (safe as Record<string, unknown>)[key] = patch[key]
    }
    const next = { ...user, ...safe }
    this.persist(next)
    return next
  }

  // -------------------------------------------------------------------------
  // Withdrawal address: the critical control
  // -------------------------------------------------------------------------

  /**
   * Request a withdrawal address.
   *
   * The first one takes effect immediately - there is nothing to protect yet,
   * since no funds can leave without it. Every later change is time-locked,
   * which is the whole point: someone who steals a Telegram session cannot
   * point the wallet at themselves and drain it before the owner notices.
   */
  requestWithdrawalAddress(
    telegramId: number,
    newAddress: Address,
    opts: { hasBalance?: boolean; nowMs?: number } = {},
  ): { applied: boolean; effectiveAt: number | null } {
    const nowMs = opts.nowMs ?? Date.now()
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')

    // First-time set is normally immediate - with no address, nothing can leave
    // yet, so there is nothing to protect. BUT if the wallet already holds funds
    // when the first address is set, an attacker who took over the account could
    // set their own address and drain instantly. In that case, time-lock it too.
    if (!user.withdrawalAddress) {
      if (opts.hasBalance) {
        const effectiveAt = nowMs + WITHDRAWAL_ADDRESS_LOCK_MS
        this.persist({ ...user, pendingWithdrawalAddress: newAddress, pendingWithdrawalEffectiveAt: effectiveAt })
        log.warn({ telegramId, newAddress }, 'first withdrawal address set with funds present - time-locked')
        return { applied: false, effectiveAt }
      }
      this.persist({ ...user, withdrawalAddress: newAddress, pendingWithdrawalAddress: null, pendingWithdrawalEffectiveAt: null })
      log.info({ telegramId, newAddress }, 'withdrawal address set (first time, immediate)')
      return { applied: true, effectiveAt: null }
    }

    if (getAddress(newAddress) === getAddress(user.withdrawalAddress)) {
      return { applied: true, effectiveAt: null }
    }

    const effectiveAt = nowMs + WITHDRAWAL_ADDRESS_LOCK_MS
    this.persist({ ...user, pendingWithdrawalAddress: newAddress, pendingWithdrawalEffectiveAt: effectiveAt })
    log.warn({ telegramId, newAddress, effectiveAt }, 'withdrawal address change requested - time-locked')
    return { applied: false, effectiveAt }
  }

  /** Apply a pending change once its lock has expired. Called before withdrawals. */
  settlePendingWithdrawal(telegramId: number, nowMs = Date.now()): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    if (
      user.pendingWithdrawalAddress &&
      user.pendingWithdrawalEffectiveAt !== null &&
      nowMs >= user.pendingWithdrawalEffectiveAt
    ) {
      const next = {
        ...user,
        withdrawalAddress: user.pendingWithdrawalAddress,
        pendingWithdrawalAddress: null,
        pendingWithdrawalEffectiveAt: null,
      }
      this.persist(next)
      log.info({ telegramId, address: next.withdrawalAddress }, 'pending withdrawal address now active')
      return next
    }
    return user
  }

  /** Cancel a pending change. The escape hatch if a hijack is caught in time. */
  cancelPendingWithdrawal(telegramId: number): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    const next = { ...user, pendingWithdrawalAddress: null, pendingWithdrawalEffectiveAt: null }
    this.persist(next)
    log.info({ telegramId }, 'pending withdrawal address change cancelled')
    return next
  }

  /**
   * The only way `frozen` changes. Kept off the generic update path so a
   * self-unfreeze can never fall out of an ordinary handler; unfreezing is an
   * operator action (see the admin command), freezing is always allowed.
   */
  setFrozen(telegramId: number, frozen: boolean): StoredUser {
    const user = this.cache.get(telegramId)
    if (!user) throw new Error('no such user')
    const next = { ...user, frozen, ...(frozen ? { armed: false } : {}) }
    this.persist(next)
    log.warn({ telegramId, frozen }, frozen ? 'account frozen' : 'account unfrozen')
    return next
  }

  /** @deprecated use setFrozen */
  freeze(telegramId: number, frozen: boolean): StoredUser {
    return this.setFrozen(telegramId, frozen)
  }
}
